#!/usr/bin/env bash
# fade-toxic.sh — the hourly queue-maintenance loop (queue-frontier C3).
#
# Runs every hour via ie.one.fade-toxic.plist:
#   1. --sync-closes   reconcile close-derived weight from learnings.md (idempotent)
#   2. --fade --rate   decay LIVE weight (strength cools, resistance heals 2× faster)
#   3. regenerate todo.md  (this loop is its ONLY writer since 2026-09-05 — the
#      per-edit/Stop/SessionStart hook that also wrote it cost 5.7s a fire)
#   4. append a one-line toxic report to the log
#
# NON-DESTRUCTIVE by contract: fades + reports only. It NEVER deletes a todo, edits a plan,
# or stages git. Toxic todos are recomputed (file state) and demoted at render time, not on
# disk. Best-effort — always exits 0; a transient failure must not wedge the launchd job.
#
# Rate: 0.02/hour ≈ 34-hour half-life for a live mark — work marked yesterday stays warm,
# work marked last week goes cold unless renewed by a fresh close/--mark. Tunable here.
#
# See text/queue-frontier-docs.md for the model; text/queue-frontier-plan.md for the design.

ROOT="${CLAUDE_PROJECT_DIR:-/Users/toc/Server/one-ie}"
RANK="$ROOT/.claude/scripts/do-rank.py"
LOGDIR="$ROOT/.claude/.cc-connect-daemon"
LOG="$LOGDIR/fade-toxic.log"
FADE_RATE="${FADE_RATE:-0.02}"

cd "$ROOT" || exit 0
mkdir -p "$LOGDIR"

TS=$(date '+%Y-%m-%d %H:%M')

# 1 + 2 — the close→weight reconcile, then the hourly live-weight decay.
python3 "$RANK" --sync-closes >/dev/null 2>&1 || true
FADED_LINE=$(python3 "$RANK" --fade --rate "$FADE_RATE" 2>/dev/null | head -1 || true)

# 3 — regenerate todo.md. `do-rank.py` is live for anything that needs it fresher than hourly.
QUEUE_OUT=$(python3 "$RANK" 2>/dev/null || true)
if [ -n "$QUEUE_OUT" ]; then
  {
    echo "# Priority queue — $TS"
    echo
    echo '```'
    echo "$QUEUE_OUT"
    echo '```'
    echo
    echo "> Auto-generated by do-rank.py (hourly fade-toxic loop). Fresher: python3 .claude/scripts/do-rank.py"
    echo "> Run \`do-rank.py --toxic\` for the demoted list, \`--frontier\` for what's next."
  } > "$ROOT/todo.md"
fi

# 4 — append a one-line toxic report (read-only projection; nothing deleted).
# Match only bare-slug lines (letters/digits/hyphens) — skips the "gate:" footer + headers.
TOX=$(python3 "$RANK" --toxic 2>/dev/null | awk '$1 ~ /^[a-z0-9][a-z0-9-]*$/ {print $1}' | paste -sd, - || true)
READY=$(python3 "$RANK" --json 2>/dev/null | python3 -c "import json,sys; print(len(json.load(sys.stdin).get('ready',[])))" 2>/dev/null || echo "?")
echo "$TS · synced+faded(${FADE_RATE}) · ready=${READY} · toxic=[${TOX:-none}]" >> "$LOG"

exit 0
