#!/usr/bin/env node
// one-agents.mjs — the BRIDGE: platform agents → Claude Code subagents.
//
// classification: monorepo-only  (hard-asserts against one.ie/ai/agents/)
//
// Reads every `kind: agent` file under one.ie/ai/agents/**.md and emits a
// spawnable Claude Code subagent into .claude/agents/one/<name>.md.
//
// WHY THIS EXISTS — the whole point of /one's desk mode:
//   A subagent starts with a FRESH context. That is exactly what a new tab
//   buys, without losing the thread. The platform org chart already names 81
//   agents with tier/reports_to/domain/subscribes; this makes them callable by
//   the Agent tool so the desk can route to them instead of the operator
//   opening another window.
//
// THE ONE HARD CONSTRAINT: a spawned subagent inherits NO parent CLAUDE.md
// (.claude/CLAUDE.md says so flatly). So the generated body INLINES the
// load-bearing substrate constants — otherwise the fresh context that solves
// the tab problem is also what makes every subagent violate the locked rules.
//
// Authority for the frontmatter shape: one.ie/web/src/lib/agent-md.ts
// (this script reads a deliberate SUBSET — name/tier/reports_to/domain/
// tagline/skills/subscribes — and never writes back).
//
// Usage:
//   node .claude/scripts/one-agents.mjs            # write .claude/agents/one/
//   node .claude/scripts/one-agents.mjs --check    # exit 1 if regeneration would change anything
//   node .claude/scripts/one-agents.mjs --chart    # print the routing table, emit nothing
//   node .claude/scripts/one-agents.mjs --models   # which model each agent gets and WHY, emit nothing
//   node .claude/scripts/one-agents.mjs --models --json   # the same as JSON on stdout (nothing written)
//   node .claude/scripts/one-agents.mjs --self-test

import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const SRC = join(ROOT, 'one.ie', 'ai', 'agents')
// FLAT, deliberately. Every agents/ directory on this machine — ten official
// plugins plus the harness itself — is flat, and not one of them nests. A
// subdirectory is unproven ground for the loader, so generated agents live
// beside w1-w4 and are told apart by the GENERATED marker, never by their path.
const OUT = join(ROOT, '.claude', 'agents')
const MARKER = '<!-- GENERATED by .claude/scripts/one-agents.mjs'

// Names the harness or the runtime already owns. Emitting one of these would
// shadow a real agent, so they are skipped loudly rather than silently.
const RESERVED = new Set([
  'claude', 'Explore', 'Plan', 'general-purpose', 'statusline-setup',
  'claude-code-guide', 'w1-recon', 'w2-decide', 'w3-edit', 'w4-verify', 'w4-tools',
])

// The Agent tool accepts ONLY these. MODEL_BY_TIER is the FALLBACK — the answer
// when the declared model is not expressible here, or when nothing is declared.
const MODEL_BY_TIER = {
  chairman: 'opus', ceo: 'opus', director: 'opus',
  specialist: 'sonnet', tool: 'haiku',
  1: 'sonnet', 2: 'sonnet', '1': 'sonnet', '2': 'sonnet',
}

// The closed set. NOTHING outside it may ever reach the Agent tool — which is
// why resolveClaudeModel returns a member of this set and NEVER the declared
// string. `fable` is legal and has no tier that produces it: it can only ever
// arrive by being declared.
const CLAUDE_MODELS = new Set(['opus', 'sonnet', 'haiku', 'fable'])

/** The Anthropic family named by an OpenRouter-shaped id, or null.
 *  Deliberately FAMILY-shaped, not an id list: `anthropic/claude-opus-5`,
 *  `claude-sonnet-4-5`, `claude-sonnet-4-6` and whatever version ships next all
 *  answer the same way, so a normalisation pass over the corpus cannot silently
 *  change which Claude Code model an agent gets. */
function claudeFamily(id) {
  const base = id.toLowerCase().split('/').pop()
  if (!base.startsWith('claude')) return null
  return base.split(/[^a-z]+/).find(w => w === 'opus' || w === 'sonnet' || w === 'haiku') ?? null
}

/**
 * Which Claude Code model this agent runs on, and WHICH RUNG SAID SO.
 *
 * Three outcomes, and the generated file names the one that happened — an agent
 * running on sonnet because its grok declaration cannot be expressed here is a
 * different fact from one running on sonnet because a human chose sonnet, and a
 * reader who cannot tell them apart will "fix" the wrong one.
 *
 *   declared  — the declared model is expressible; it travels.
 *   fallback  — declared, but an OpenRouter id Claude Code cannot run (grok,
 *               kimi). A real limit of this bridge, not a bug in the agent.
 *   tier      — nothing declared. Since C14 an absent `model:` means the
 *               PLATFORM default at runtime (`DEFAULT_MODEL = 'x-ai/grok-4.5'`,
 *               packages/sdk/src/billing.ts) — also not expressible here, so
 *               absent lands on tier for the same honest reason grok does.
 *
 * @returns {{model: string, source: 'declared'|'fallback'|'tier', note: string}}
 */
function resolveClaudeModel(declared, tier) {
  const fallback = MODEL_BY_TIER[tier] ?? 'sonnet'
  const d = typeof declared === 'string' ? declared.trim() : ''
  if (!d) return { model: fallback, source: 'tier', note: `${fallback} (tier — no model declared)` }
  if (CLAUDE_MODELS.has(d.toLowerCase())) {
    const m = d.toLowerCase()
    return { model: m, source: 'declared', note: `${m} (declared ${d})` }
  }
  const fam = claudeFamily(d)
  if (fam) return { model: fam, source: 'declared', note: `${fam} (declared ${d})` }
  return {
    model: fallback,
    source: 'fallback',
    note: `${fallback} (tier fallback — declared ${d} is not expressible in Claude Code)`,
  }
}

// Engineering agents touch the repo; everyone else touches the world.
const TOOLS_ENGINEERING = 'Read, Grep, Glob, Bash, Edit, Write, WebFetch'
const TOOLS_WORLD = 'Read, Grep, Glob, Bash, Write, WebFetch, WebSearch'
const TOOLS_DIRECTOR = 'Read, Grep, Glob, Bash, WebFetch, WebSearch'

const COLOR_BY_DOMAIN = {
  governance: 'purple', engineering: 'blue', marketing: 'orange',
  sales: 'green', service: 'cyan', education: 'yellow',
  finance: 'green', community: 'pink',
}

// ---------------------------------------------------------------- frontmatter

/** Minimal YAML-subset reader. Scalars, `[a, b]` inline lists, and `- item`
 *  block lists — which is everything these files actually use. Deliberately
 *  NOT a YAML parser: an unparseable value yields undefined and the agent is
 *  skipped, which is the safe direction. */
function frontmatter(text) {
  if (!text.startsWith('---')) return null
  const end = text.indexOf('\n---', 3)
  if (end === -1) return null
  const head = text.slice(4, end)
  const body = text.slice(end + 4).replace(/^\n+/, '')
  const meta = {}
  let key = null
  for (const raw of head.split('\n')) {
    const line = raw.replace(/\s+$/, '')
    if (!line || line.startsWith('#')) continue
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/)
    if (m) {
      key = m[1]
      const v = m[2].trim()
      if (v === '') { meta[key] = []; continue }
      if (v.startsWith('[') && v.endsWith(']')) {
        meta[key] = v.slice(1, -1).split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
        key = null
        continue
      }
      meta[key] = v.replace(/^["']|["']$/g, '')
      key = null
      continue
    }
    const item = line.match(/^\s*-\s+(.*)$/)
    if (item && key) {
      if (!Array.isArray(meta[key])) meta[key] = []
      // `- signal: campaign:brief` appears in the wild — keep the value half.
      const val = item[1].replace(/^signal:\s*/, '').trim().replace(/^["']|["']$/g, '')
      if (val) meta[key].push(val)
    }
  }
  return { meta, body }
}

function walk(dir, acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) walk(p, acc)
    else if (e.name.endsWith('.md')) acc.push(p)
  }
  return acc
}

// ------------------------------------------------------------------- collect

const SKIPPED = []

function collect() {
  const out = []
  const seen = new Map()
  for (const path of walk(SRC).sort()) {
    const rel = relative(ROOT, path)
    let parsed
    try { parsed = frontmatter(readFileSync(path, 'utf8')) } catch { parsed = null }
    if (!parsed) { SKIPPED.push([rel, 'no frontmatter']); continue }
    const { meta, body } = parsed

    // `kind: agent` is the gate. It excludes AGENTS.md, README.md, the
    // import-*/export-* connector stubs, and the doc files that live here.
    if (meta.kind !== 'agent') { SKIPPED.push([rel, `kind=${meta.kind ?? '-'}`]); continue }

    const name = String(meta.name ?? '').trim()
    // The template file declares `name: <kebab-case>` with placeholder
    // frontmatter. Without this guard the generator emits a subagent literally
    // called `<kebab-case>`.
    if (!/^[a-z][a-z0-9-]*$/.test(name)) { SKIPPED.push([rel, `bad name: ${name || '(none)'}`]); continue }
    if (RESERVED.has(name)) { SKIPPED.push([rel, 'reserved name']); continue }
    if (meta.lifecycle && meta.lifecycle !== 'active') { SKIPPED.push([rel, `lifecycle=${meta.lifecycle}`]); continue }
    if (seen.has(name)) { SKIPPED.push([rel, `duplicate of ${seen.get(name)}`]); continue }

    seen.set(name, rel)
    out.push({
      name,
      src: rel,
      tier: String(meta.tier ?? 'specialist'),
      // The RAW declared value, or undefined. Nothing fills a default here: this
      // script parses the file itself (`frontmatter(readFileSync(...))` above),
      // never the web loader — which since C14 fills the platform default in and
      // would make every single agent read as `declared`.
      model: meta.model ? String(meta.model) : undefined,
      reports_to: meta.reports_to ? String(meta.reports_to) : null,
      domain: String(meta.domain ?? 'governance'),
      title: meta.title ? String(meta.title) : name,
      tagline: meta.tagline ? String(meta.tagline) : '',
      skills: Array.isArray(meta.skills) ? meta.skills : (meta.skills ? [String(meta.skills)] : []),
      subscribes: (Array.isArray(meta.subscribes) ? meta.subscribes : []).filter(t => t !== '*'),
      body,
    })
  }
  return out
}

// -------------------------------------------------------------------- render

/** The constants a subagent cannot look up, because it inherits no CLAUDE.md.
 *  Everything here is LOCKED in the substrate — a subagent that renames one of
 *  these breaks the schema, not just its own reply. */
const SUBSTRATE = `
## Substrate constants (you inherit no CLAUDE.md — these are the locked facts)

You are running inside the ONE monorepo at \`/Users/toc/Server/one-ie\`.

**6 dimensions (LOCKED, never rename):** Groups · Actors · Things · Paths · Events · Learning.
Dead names that must never appear: knowledge, connections, people, node, scent, alarm, trail, colony.

**6 verbs (LOCKED):** \`signal\` · \`mark\` · \`warn\` · \`fade\` · \`follow\` · \`harden\`.
Every signal closes with \`mark()\`, \`warn()\`, or dissolve. **No silent returns.**

**Tags are BARE words** — \`marketing\`, \`lead\`, \`engineering\` — never \`lifecycle:marketing\`.
A namespaced subscribe tag matches zero signals.

**Structural time** — plan in tasks → waves → cycles. Never days/hours/weeks.

**Where things live:** web UI + API routes \`one.ie/web/\` · TypeDB schema \`schema/\` (never
duplicate .tql elsewhere) · specs and docs \`text/\` · payments \`pay/\` · agent runtime \`channels/\`.
Backend routes live ONLY in \`one.ie/web/src/pages/api/\`.

**Tests:** \`bun run verify:fast\` is the dev lane; the full \`bun run verify\` (~87s) is the review
gate. Say which lane you ran — a fast pass is never reported as a full pass. A test touching the
DOM needs \`// @vitest-environment jsdom\` on line 1.

**Where you collaborate, and where you plan.** \`/u/<slug>/in\` is the room. Its Spaces ARE
your \`subscribes:\` tags — \`FN_TAGS\` maps a department to bare words
(\`one.ie/web/src/lib/in/spaces.ts:28\`), so staking \`marketing\` IS having a desk in the
marketing Space. \`/u/<slug>/tasks\` is the same words as plannable rows.

**A task comment is a message in that room — one store, one renderer, one vocabulary.**
\`tasks:comment\` writes to the SAME D1 message store the inbox thread uses
(\`one.ie/web/src/lib/resolvers/tasks.ts:1639\`, thread id \`task:<tid>\` at \`:1665\`), and it
renders through the same \`Thread\` component the conversation uses
(\`one.ie/web/src/components/in/TaskDetail.tsx:13,859\`). An \`@mention\` in a comment body
INSERTs a \`follows\` row (\`resolvers/tasks.ts:1686-1693\`) — mentioning someone subscribes
them to that task. So: report where the work already is. Never open a second room, and never
invent a second vocabulary — the tag that routes your signal is the same word that names your
Space and tags the task.

**Proof discipline:** a presence grep is not proof. Probe the running thing. Report numbers you
actually measured, and say plainly when a check did not run — an unrun gate is not a pass.

## The four verbs of working together — claim · delegate · chat · chain

A meeting is not where you report. It is where you **take a row, hand a row, argue on the row,
and put the rows in order.** All four are receivers; none is a convention you can improvise.

    claim     tasks:claim    {"data":{"tid":"task:<24hex>","workspace":"<slug>"}}
    delegate  tasks:reassign {"data":{"tid":"...","assignee":"<slug>","workspace":"..."}}
              tasks:announce {"data":{"taskId":"...","tags":["bare","words"],"workspace":"..."}}
    chat      tasks:comment  {"data":{"tid":"...","workspace":"...","body":"..."}}
              thread:append  {"data":{"slug":"one","group":"space:one","sender":"<you>","role":"assistant","content":"..."}}
    chain     tasks:subtask  {"data":{"parent":"task:...","title":"...","blockedBy":["task:..."],"workspace":"..."}}
              tasks:depend   {"data":{"tid":"task:<blocked>","blockedBy":"task:<blocker>","workspace":"..."}}

**CHAINING IS NOT BOOKKEEPING — it is what makes the board sequence itself.** \`tasks:claim\`
is **blocker-gated**, and \`tasks:depend\` writes the very \`blocks\` edge that gate reads. So an
unchained board hands every agent every row at once and nothing knows what comes first; a chained
one refuses a claim whose prerequisites are still open. **Chain before you fan out, or the fan-out
is a race.** \`tasks:depend\` refuses a self-edge and a reverse edge, so a cycle cannot be filed.

**\`tasks:subtask\` is the verb for splitting work, not \`tasks:create\`.** It writes the row, its
notes, its tags, its \`containment\` edge to the parent AND every \`blockedBy\` prerequisite in ONE
pipeline — precisely so a child never appears claimable with an empty body or missing ordering.
A child made with \`tasks:create\` is an orphan that somebody will claim before it is ready.

**Delegation moves a row; it does not copy one.** \`tasks:reassign\` swaps the \`@<slug>\` tag in
place and announces on the new tag set. An empty assignee unassigns and moves a \`picked\` row back
to \`open\` — claimable means **open AND unassigned**. Never "delegate" by filing a second task:
that is how a board grows a duplicate \`Handle: <title>\` row for work that already had one.

**\`tasks:announce\` returns \`matched\`, and matched is not delivered.** It reports how many staked
actors the tags reached, not how many acted. Quote it as reach; never as done.

**The claimant is the attested caller, never a body field.** You cannot claim on someone else's
behalf — hand them the row with \`tasks:reassign\` and let them claim it. **Under the shared
gateway key the attested caller is the workspace, so every head's claim lands as \`@one\`** — follow
\`tasks:claim\` with \`tasks:reassign {assignee: "<your slug>"}\` in the same breath, or the ledger
cannot say who took the row.

**Two rules that keep a chain honest**, and they are the same rule twice:
- **A child's cast is a subset of its parent's.** Inherit by default, declare to narrow, **never
  declare to widen.** A leaf must not quietly attach a stakeholder the parent never had.
- **Depth needs a floor.** A parent that spawns children without any settling is a leak, not a
  big plan. Freeze the parent's outcome before its children mint, and let \`fade\`/\`warn\` decay
  what goes quiet.

**No agent leaves a meeting without a tid.** Claimed, delegated (name who to), chained (name the
parent), or **declined with an argument** — a refusal on principle is sometimes the best act
available. "Blocked" with no named blocker is not a status, it is a shrug. A meeting whose output
is a document and no moved row has failed, however good the document.
`.trim()

/** How many agents stake each tag — used to drop the non-discriminating ones
 *  from descriptions. Rebuilt per render call set; cheap at this size. */
let STAKE_FREQ = new Map()
function indexStakes(roster) {
  STAKE_FREQ = new Map()
  for (const a of roster) for (const t of a.subscribes) STAKE_FREQ.set(t, (STAKE_FREQ.get(t) ?? 0) + 1)
}

function render(a, roster) {
  if (STAKE_FREQ.size === 0) indexStakes(roster)
  const resolved = resolveClaudeModel(a.model, a.tier)
  const model = resolved.model
  const isDirector = a.tier === 'director' || a.tier === 'ceo' || a.tier === 'chairman'
  const tools = isDirector ? TOOLS_DIRECTOR
    : a.domain === 'engineering' ? TOOLS_ENGINEERING
    : TOOLS_WORLD
  const color = COLOR_BY_DOMAIN[a.domain] ?? 'blue'

  // The description is what the Agent tool matches on when deciding whether to
  // spawn this agent, so it must be TRIGGER-shaped — the tags it stakes on —
  // not a job title.
  //
  // KEEP IT SHORT. Every description here is injected into the roster
  // system-reminder on EVERY turn of EVERY session in this repo, desk or not.
  // 80 agents is the difference between a few hundred tokens and several
  // thousand of standing tax — and this design's whole thesis is that the tab
  // stays light. So the description carries trigger words only. Tier, domain
  // and reporting line are already in the body, where the spawned agent reads
  // them, and none of the three helps the router decide to spawn this agent.
  // Prefer DISCRIMINATING tags. `lead, mql, sql, marketing` is the department
  // stake ~30 agents share — it costs bytes on every turn and tells the router
  // nothing about which of the thirty to pick. `campaign:<id>:copy-needed`
  // does. Fall back to the shared tags only when an agent has nothing else.
  const own = a.subscribes.filter(t => (STAKE_FREQ.get(t) ?? 0) <= 5)
  const stake = (own.length ? own : a.subscribes.length ? a.subscribes : [a.domain]).slice(0, 4).join(', ')
  const desc = [
    (a.tagline || `${a.title}.`).replace(/\s+/g, ' ').trim(),
    `For: ${stake}.`,
  ].join(' ').replace(/"/g, "'")

  const reports = roster.filter(r => r.reports_to === a.name).map(r => r.name)
  // The delegation line is tier-shaped. "You are a director, not a specialist"
  // reads as a demotion on the top rung, whose whole function is that nobody is
  // checking it — so the chairman gets the sentence its own job actually needs.
  const delegation = a.tier === 'chairman'
    ? `You are the top rung — nobody audits you, so ask what was MEASURED, never what was\nclaimed. Convene, press for the second answer, name disagreements. Do not do their work yourself.`
    : `You are a director, not a specialist — decide which work is worth doing, name the agent\nthat owns the surface, and report back. Do not do their work yourself.`
  const chain = reports.length
    ? `\n## Your reports\n\nThese agents report to you and are spawnable by name: ${reports.join(' · ')}.\n${delegation}\n`
    : ''

  // The provenance line goes in the MARKER block, NOT as a YAML comment inside
  // the frontmatter. Measured: not one agent file Claude Code loads on this box
  // carries a `#` line inside its frontmatter (0 of the 96 generated + 5
  // hand-written), so a YAML comment there is unproven ground — and the failure
  // would land on all 96 files at once, at a regeneration nobody is watching.
  // The HTML comment below is proven to survive: it is the first line of every
  // spawned agent's own system prompt.
  return `---
name: ${a.name}
description: "${desc}"
tools: "${tools}"
model: ${model}
color: ${color}
---
${MARKER} from ${a.src} — do not hand-edit.
     model: ${resolved.note}
     Edit the platform agent, then re-run the generator. -->

${SUBSTRATE}
${chain}
---

${a.body.trim()}

---

## Closing the loop

Return a compact report: what you found or did, the file:line evidence, and one
sentence naming what you did NOT do. If you were asked for something you cannot
verify, say so — do not fill the gap with a plausible answer.
`
}

// ---------------------------------------------------------------------- main

const args = process.argv.slice(2)

if (args.includes('--self-test')) {
  let fail = 0
  const ok = (label, cond) => { console.log(`${cond ? 'ok  ' : 'FAIL'} ${label}`); if (!cond) fail++ }

  const fm = frontmatter('---\nname: x\nskills: [a, b]\nsubscribes:\n  - lead\n  - signal: route:to-x\n---\nbody here\n')
  ok('scalar parsed', fm.meta.name === 'x')
  ok('inline list parsed', JSON.stringify(fm.meta.skills) === '["a","b"]')
  ok('block list parsed', JSON.stringify(fm.meta.subscribes) === '["lead","route:to-x"]')
  ok('body split', fm.body.trim() === 'body here')
  ok('no frontmatter -> null', frontmatter('# hello') === null)

  // RED PROOF: the placeholder-name guard must actually bite. Without it the
  // generator emits a subagent named `<kebab-case>`.
  ok('placeholder name rejected', !/^[a-z][a-z0-9-]*$/.test('<kebab-case>'))
  ok('reserved name held', RESERVED.has('w1-recon'))
  // RED PROOF: an OpenRouter model id must never reach the Agent tool.
  ok('grok id never mapped through', !Object.values(MODEL_BY_TIER).some(m => m.includes('/')))

  // RED PROOFS for C16 — a declared Claude model must TRAVEL, and the generated
  // file must SAY which of the three things happened. Literal fixtures, never
  // corpus rows: exactly one agent declares opus today, so a corpus-keyed test
  // would go red the moment that file is renamed.
  const fx = (tier, model) => ({
    name: 'fx', src: 'fx.md', tier, reports_to: null, domain: 'engineering',
    title: 'Fixture', tagline: 'A fixture.', skills: [], subscribes: [], body: 'fixture body', model,
  })
  const declaredOpus = render(fx('specialist', 'anthropic/claude-opus-5'), [])
  ok('declared opus travels', /^model: opus$/m.test(declaredOpus))
  ok('declared opus says declared', declaredOpus.includes('model: opus (declared anthropic/claude-opus-5)'))
  const declaredGrok = render(fx('specialist', 'x-ai/grok-4.5'), [])
  ok('grok falls back to tier', /^model: sonnet$/m.test(declaredGrok))
  ok('grok never travels verbatim', !declaredGrok.includes('x-ai/grok-4.5\n') && !/^model: .*\//m.test(declaredGrok))
  ok('grok says tier fallback', declaredGrok.includes('model: sonnet (tier fallback — declared x-ai/grok-4.5 is not expressible in Claude Code)'))
  const noModel = render(fx('specialist', undefined), [])
  ok('no model declared falls back to tier', /^model: sonnet$/m.test(noModel))
  ok('no model declared says so', noModel.includes('model: sonnet (tier — no model declared)'))
  // The family map must be version-agnostic — C15 is normalising these ids right now.
  ok('bare claude-sonnet-4-5 is expressible', /^model: sonnet$/m.test(render(fx('director', 'claude-sonnet-4-5'), [])))
  ok('bare `sonnet` is expressible', /^model: sonnet$/m.test(render(fx('director', 'sonnet'), [])))
  ok('fable stays a legal declared value', /^model: fable$/m.test(render(fx('specialist', 'fable'), [])))
  ok('a director declaring haiku is honoured over its tier', /^model: haiku$/m.test(render(fx('director', 'anthropic/claude-haiku-4-5'), [])))
  // C15 measured that OpenRouter's real ids use DOTS, not hyphens, for the
  // version (`grok-4.5`), and 78 of 105 declared ids are not served at all — so
  // the normalisation landing beside this one will rewrite the version
  // separator. The family map must not care, and here is the proof that it does
  // not: hyphen, dot, prefixed, unprefixed, all four answer the same.
  ok('a dotted version resolves (anthropic/claude-sonnet-4.5)', /^model: sonnet$/m.test(render(fx('director', 'anthropic/claude-sonnet-4.5'), [])))
  ok('a dotted unprefixed version resolves (claude-opus-4.6)', /^model: opus$/m.test(render(fx('specialist', 'claude-opus-4.6'), [])))
  ok('a dotted haiku resolves (anthropic/claude-haiku-4.5)', /^model: haiku$/m.test(render(fx('ceo', 'anthropic/claude-haiku-4.5'), [])))
  ok('a non-claude vendor id never resolves to a family', claudeFamily('x-ai/grok-4.5') === null && claudeFamily('moonshotai/kimi-k3') === null)

  const roster = collect()
  ok(`roster non-empty (${roster.length})`, roster.length > 20)
  ok('no placeholder in roster', !roster.some(r => r.name.includes('<')))
  // RED PROOF, STRENGTHENED for C16. Until a declared model could travel, this
  // assertion read MODEL_BY_TIER[r.tier] — the table, not the emitted value —
  // and so did `grok id never mapped through` above. Both were true and both
  // were BLIND to the declared path, which is now the only way an OpenRouter id
  // could reach the Agent tool. Assert on what render() actually writes, for
  // every real roster row.
  ok('every RESOLVED roster model is legal', roster.every(r => CLAUDE_MODELS.has(resolveClaudeModel(r.model, r.tier).model)))
  const emitted = roster.map(r => (render(r, roster).match(/^model: (.*)$/m) ?? [])[1])
  ok('no OpenRouter id reaches the Agent tool', emitted.every(m => CLAUDE_MODELS.has(m)))
  ok('no emitted model carries a vendor slash', emitted.every(m => m && !m.includes('/')))
  ok('every agent says which rung chose its model', roster.every(r => /\n     model: .+ \((declared |tier)/.test(render(r, roster))))
  const ceo = roster.find(r => r.name === 'ceo')
  ok('ceo present', !!ceo)
  ok('ceo drops the "*" wildcard subscribe', ceo && !ceo.subscribes.includes('*'))
  const rendered = ceo ? render(ceo, roster) : ''
  ok('render inlines substrate constants', rendered.includes('6 verbs (LOCKED)'))
  ok('render names the reports', rendered.includes('cto'))
  ok('render carries the sweep marker', rendered.includes(MARKER))

  // RED PROOF for the flat layout. The sweep deletes generated strays from a
  // directory it SHARES with the hand-written harness agents, so the marker
  // test is the only thing standing between a regenerate and losing w1-w4.
  // Assert directly that they carry no marker and would therefore be invisible
  // to it — and that a generated file WOULD be seen.
  const HAND = ['w1-recon.md', 'w2-decide.md', 'w3-edit.md', 'w4-verify.md', 'w4-tools.md']
  const survives = HAND.filter(f => {
    const p = join(OUT, f)
    return !existsSync(p) || !readFileSync(p, 'utf8').includes(MARKER)
  })
  ok(`sweep cannot see the ${HAND.length} hand-written harness agents`, survives.length === HAND.length)

  // Every description is injected into the roster reminder on EVERY turn of
  // EVERY session in this repo. This is the standing tax the design pays, so
  // it is asserted, not assumed. ~90 chars x 80 agents ~= 7KB ~= 1.8k tokens.
  const descBytes = roster.reduce((n, a) => n + render(a, roster).split('\n')[2].length, 0)
  ok(`roster description budget ${(descBytes / 1024).toFixed(1)}KB < 14KB`, descBytes < 14 * 1024)

  console.log(fail === 0 ? `\nPASS — ${roster.length} agents` : `\nFAIL — ${fail} check(s)`)
  process.exit(fail === 0 ? 0 : 1)
}

const roster = collect()

if (args.includes('--models')) {
  const rows = roster.map(a => ({ name: a.name, tier: a.tier, declared: a.model ?? null, ...resolveClaudeModel(a.model, a.tier) }))
  const tally = { declared: 0, fallback: 0, tier: 0 }
  for (const r of rows) tally[r.source]++
  if (args.includes('--json')) {
    console.log(JSON.stringify({ total: rows.length, tally, agents: rows }, null, 2))
    process.exit(0)
  }
  for (const r of rows.sort((x, y) => x.source.localeCompare(y.source) || x.name.localeCompare(y.name))) {
    console.log(`  ${r.name.padEnd(28)} ${r.model.padEnd(7)} ${r.source.padEnd(9)} ${r.declared ?? '(none declared)'}`)
  }
  console.log(`\n${rows.length} agents — declared ${tally.declared} · tier fallback ${tally.fallback} · no model declared ${tally.tier}`)
  process.exit(0)
}

if (args.includes('--chart')) {
  const byDomain = {}
  for (const a of roster) (byDomain[a.domain] ??= []).push(a)
  console.log(`# ONE routing table — ${roster.length} spawnable agents\n`)
  for (const d of Object.keys(byDomain).sort()) {
    const list = byDomain[d]
    const heads = list.filter(a => a.tier === 'director' || a.tier === 'ceo')
    console.log(`## ${d}  (${list.length})${heads.length ? '  — head: ' + heads.map(h => h.name).join(', ') : ''}`)
    for (const a of list.sort((x, y) => x.name.localeCompare(y.name))) {
      console.log(`  ${a.name.padEnd(28)} ${a.tier.padEnd(11)} ${(a.subscribes.slice(0, 5).join(',') || '-')}`)
    }
    console.log('')
  }
  console.log(`skipped ${SKIPPED.length}:`)
  for (const [f, why] of SKIPPED) console.log(`  ${f} — ${why}`)
  process.exit(0)
}

const files = new Map()
for (const a of roster) files.set(`${a.name}.md`, render(a, roster))

/** The files WE wrote, identified by the marker in their body and never by
 *  filename. This is the whole reason a flat directory is safe: w1-recon.md and
 *  the other hand-written harness agents carry no marker, so the sweep below
 *  cannot see them. */
function generatedOnDisk() {
  if (!existsSync(OUT)) return []
  return readdirSync(OUT)
    .filter(f => f.endsWith('.md'))
    .filter(f => { try { return readFileSync(join(OUT, f), 'utf8').includes(MARKER) } catch { return false } })
}

if (args.includes('--check')) {
  let drift = 0
  const existing = new Set(generatedOnDisk())
  for (const [f, content] of files) {
    const p = join(OUT, f)
    const cur = existsSync(p) ? readFileSync(p, 'utf8') : null
    if (cur !== content) { console.log(`DRIFT ${f}${cur === null ? ' (missing)' : ''}`); drift++ }
    existing.delete(f)
  }
  for (const f of existing) { console.log(`STALE ${f}`); drift++ }
  console.log(drift === 0 ? `ok — ${files.size} agents in sync` : `\n${drift} file(s) out of sync — run: node .claude/scripts/one-agents.mjs`)
  process.exit(drift === 0 ? 0 : 1)
}

mkdirSync(OUT, { recursive: true })
let swept = 0
for (const f of generatedOnDisk()) if (!files.has(f)) { rmSync(join(OUT, f)); swept++ }

// Guard the WRITE the same way the delete is guarded. RESERVED only knows the
// five harness agents that exist today; a hand-written agent added tomorrow
// whose name collides with a platform agent would be silently overwritten —
// and would then carry the marker, so the next sweep would own it too. Refuse
// loudly instead.
let refused = 0
for (const [f, content] of files) {
  const p = join(OUT, f)
  if (existsSync(p) && !readFileSync(p, 'utf8').includes(MARKER)) {
    console.log(`REFUSE ${f} — hand-written file, not overwriting (rename the platform agent)`)
    refused++
    continue
  }
  writeFileSync(p, content)
}
if (refused) console.log(`${refused} agent(s) refused`)
console.log(`wrote ${files.size} agents -> ${relative(ROOT, OUT)}/  (skipped ${SKIPPED.length}, swept ${swept})`)
console.log('NOTE: the roster is read at SESSION START — restart the session before spawning these.')
