#!/usr/bin/env python3
"""Build the inbound-prompt corpus from Claude Code session transcripts.

Every inbound user-role message across every session in this project, sorted by
timestamp, classified by WHAT IT IS. The point is the classification: the
operator's own words turn out to be ~5% of inbound text and the other 95% is
machine envelope — standing fan-out prompts, subagent completion reports,
command bodies, skill bodies. You cannot optimise what you have not separated.

    python3 .claude/scripts/prompt-corpus.py            # summary to stdout
    python3 .claude/scripts/prompt-corpus.py --json OUT # + full corpus as JSON
    python3 .claude/scripts/prompt-corpus.py --days 14  # recency window

RECENCY IS NOT OPTIONAL. Ranked all-time, the top line item was 53% of a month's
inbound text and had not fired in five days — and was generated by a third-party
plugin, not by anything in this repo. Rank by the window, then ask who owns the
generator. `text/prompt-streamline-plan.md` records that trap.
"""
import json
import glob
import os
import re
import sys
import collections
import datetime
import statistics

PROJ = os.path.expanduser("~/.claude/projects/-Users-toc-Server-one-ie")


def classify(c: str) -> str:
    """What kind of thing is this inbound message? Order matters — first match wins."""
    if c.startswith("<task-notification>"):
        return "task-notify"
    if c.startswith("<command-name>") or c.startswith("<command-message>"):
        return "cmd-echo"
    if c.startswith("Base directory for this skill"):
        return "skill-body"
    if c.startswith("[Request interrupted"):
        return "interrupt"
    if c.startswith("[Image:"):
        return "image"
    if c.startswith("Launch the ") or c.startswith("Review this change for security"):
        return "standing-prompt"
    if re.match(r"^#\s+/?[\w-]", c) and len(c) > 400:
        return "cmd-body"
    return "human"


def bucket(c: str):
    """A stable name for a repeated prompt SHAPE, or None if it is one-of-a-kind."""
    m = re.match(
        r"^(Launch the [\w-]+ agent|Review this change for security|# /[\w-]+"
        r"|# Claude Code Doctor|# Workflow authoring reference|Base directory for this skill)",
        c,
    )
    if m:
        return m.group(1)
    if c.startswith("<task-notification>"):
        return "<task-notification>"
    return None


def load():
    rows = []
    for f in glob.glob(os.path.join(PROJ, "*.jsonl")):
        for line in open(f, errors="ignore"):
            try:
                d = json.loads(line)
            except Exception:
                continue
            if d.get("type") != "user":
                continue
            msg = d.get("message", {})
            c = msg.get("content")
            if isinstance(c, list):
                c = " ".join(
                    x.get("text", "") for x in c
                    if isinstance(x, dict) and x.get("type") == "text"
                )
            if not isinstance(c, str) or not c.strip():
                continue
            # System reminders are injected by the harness, not sent by anyone.
            c = re.sub(r"<system-reminder>.*?</system-reminder>", "", c, flags=re.S).strip()
            if not c:
                continue
            ts = d.get("timestamp", "")
            rows.append({
                "f": os.path.basename(f)[:8], "ts": ts, "date": ts[:10],
                "kind": classify(c), "len": len(c), "text": c,
            })
    rows.sort(key=lambda r: r["ts"])
    return rows


def main():
    days = 14
    out = None
    if "--days" in sys.argv:
        days = int(sys.argv[sys.argv.index("--days") + 1])
    if "--json" in sys.argv:
        out = sys.argv[sys.argv.index("--json") + 1]

    rows = load()
    if not rows:
        print("no transcripts found under", PROJ)
        return 1
    total = sum(r["len"] for r in rows)
    today = datetime.date.today()

    def age(r):
        return (today - datetime.date(*map(int, r["date"].split("-")))).days

    print(f"rows {len(rows)}  span {rows[0]['date']} → {rows[-1]['date']}  "
          f"{total:,} chars ≈ {total // 4:,} tok")
    print("\n  kind              n      chars       ~tok   share")
    byk, ch = collections.Counter(), collections.Counter()
    for r in rows:
        byk[r["kind"]] += 1
        ch[r["kind"]] += r["len"]
    for k, v in ch.most_common():
        print(f"  {k:14s} {byk[k]:5d} {v:10,d} {v // 4:10,d}  {100 * v / total:5.1f}%")
    print(f"\n  human words are {100 * ch['human'] / total:.1f}% of inbound text")

    agg = collections.defaultdict(
        lambda: {"n": 0, "ch": 0, "first": "9", "last": "0", "nw": 0, "chw": 0})
    for r in rows:
        k = bucket(r["text"])
        if not k:
            continue
        a = agg[k]
        a["n"] += 1
        a["ch"] += r["len"]
        a["first"] = min(a["first"], r["date"])
        a["last"] = max(a["last"], r["date"])
        if age(r) <= days:
            a["nw"] += 1
            a["chw"] += r["len"]
    print(f"\nrepeated prompt shapes, ranked by the LAST {days} DAYS (all-time is history):")
    print(f"  {'shape':34s} {'n':>5s} {'alltok':>9s} {'last':>11s} "
          f"{'n/' + str(days) + 'd':>6s} {'tok/' + str(days) + 'd':>10s}")
    for k, a in sorted(agg.items(), key=lambda x: -x[1]["chw"]):
        print(f"  {k[:34]:34s} {a['n']:5d} {a['ch'] // 4:9,d} {a['last']:>11s} "
              f"{a['nw']:6d} {a['chw'] // 4:10,d}")

    tn = [r for r in rows if r["kind"] == "task-notify"]
    if tn:
        L = sorted(r["len"] for r in tn)
        fat = sum(L[int(len(L) * .95):])
        print(f"\ntask-notify (subagent reports): n={len(tn)}  p50={int(statistics.median(L))}  "
              f"p95={L[int(len(L) * .95)]}  max={max(L):,}")
        print(f"  top 5% carry {100 * fat / sum(L):.0f}% of the bytes — the fat tail IS the target")

    if out:
        json.dump(rows, open(out, "w"))
        print(f"\nwrote {out} ({os.path.getsize(out):,} bytes) — slice it with python, never read it whole")
    return 0


if __name__ == "__main__":
    sys.exit(main())
