#!/usr/bin/env bash
# retro.sh — look back at the conversations, then make the next person's path shorter.
#
# THE ONE RULE THIS SCRIPT EXISTS TO ENFORCE: a learning that lands in a report is
# worth nothing. It must land in a file that AUTO-LOADS for the next person on that
# path, or the next person pays the same cost again. So this script's last section is
# not the findings — it is the list of doors a finding can be written through, with the
# glob that decides who loads it. The measurement is the cheap part.
#
#   bash .claude/scripts/retro.sh              # last 7 days
#   bash .claude/scripts/retro.sh --days 14
#   bash .claude/scripts/retro.sh --out FILE   # also write the brief to FILE
#
# Deterministic and free: no model call, no network. Everything here is counted, so a
# session reading the brief spends its tokens deciding, not measuring.
set -uo pipefail

DAYS=7
OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --days) DAYS="${2:-7}"; shift 2 ;;
    --out)  OUT="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT" || exit 1
PROJ="$HOME/.claude/projects"

emit() { if [ -n "$OUT" ]; then printf '%s\n' "$*" | tee -a "$OUT"; else printf '%s\n' "$*"; fi; }
# Run a command and route ITS output through emit as well. Without this, a --out brief
# silently loses every generated section and reads as an empty retro — measured, and the
# exact failure this script warns about elsewhere: a short answer that does not say so.
emit_cmd() { local line; while IFS= read -r line; do emit "  $line"; done < <("$@" 2>&1); }
[ -n "$OUT" ] && : > "$OUT"

TMPD="$(mktemp -d)"; trap 'rm -rf "$TMPD"' EXIT

emit "# RETRO — last $DAYS days · $(date -u +%Y-%m-%dT%H:%MZ)"
emit ""
emit "Generated by \`.claude/scripts/retro.sh --days $DAYS\`. Every number below is counted,"
emit "not estimated. Spend your tokens on the DECISION, not on re-measuring."
emit ""

# ── 1 · what entered context, by kind ────────────────────────────────────────
emit "## 1 · What entered context"
emit ""
emit '```'
if [ -f .claude/scripts/prompt-corpus.py ]; then
  emit_cmd python3 .claude/scripts/prompt-corpus.py --days "$DAYS"
else
  emit "  prompt-corpus.py ABSENT — cannot measure the corpus (see text/prompt-streamline-plan.md)"
fi
emit '```'
emit ""
emit "Read it as: the operator's own words are the small share. The cost is the envelope"
emit "around him. Rank by the WINDOW, and ask who owns each generator before proposing a fix —"
emit "an all-time #1 that stopped firing, or that a third-party plugin emits, is not a target."
emit ""

# ── 2 · friction: where he had to say it twice ────────────────────────────────
emit "## 2 · Friction — where the operator repeated himself"
emit ""
emit "These are the moments the next person should never reach. Each one is a candidate"
emit "learning; the fix belongs in a door from section 4."
emit ""
emit '```'
cat > "$TMPD/friction.py" <<'PY'
import json, glob, os, re, sys, collections, datetime
days = int(sys.argv[1])
proj = os.path.expanduser("~/.claude/projects")
# Every transcript dir for this repo, including worktree-scoped ones.
files = []
for d in glob.glob(proj + "/-Users-toc-Server-one-ie*"):
    files += glob.glob(d + "/*.jsonl")
cutoff = (datetime.date.today() - datetime.timedelta(days=days)).isoformat()
CORRECT = re.compile(
    r"\b(no,|not what|i said|wrong|why did you|you should have|stop|dont|don't|wtf|"
    r"again|still (not|broken|doesn't)|check again|actually)\b", re.I)
RESTART = re.compile(
    r"\b(keep going|continue|carry on|resume|why did you stop|finish (it|them)|go on)\b", re.I)
rows, interrupts = [], 0
for f in files:
    for line in open(f, errors="ignore"):
        if '"type":"user"' not in line and '"type": "user"' not in line:
            continue
        try:
            d = json.loads(line)
        except Exception:
            continue
        if d.get("type") != "user":
            continue
        ts = d.get("timestamp", "")
        if ts[:10] < cutoff:
            continue
        c = d.get("message", {}).get("content")
        if isinstance(c, list):
            c = " ".join(x.get("text", "") for x in c
                         if isinstance(x, dict) and x.get("type") == "text")
        if not isinstance(c, str):
            continue
        c = re.sub(r"<system-reminder>.*?</system-reminder>", "", c, flags=re.S).strip()
        if not c:
            continue
        if c.startswith("[Request interrupted"):
            interrupts += 1
            continue
        # machine envelope is not the operator
        if c[:1] in "<#" or c.startswith("Base directory for this skill") \
           or c.startswith("Launch the ") or c.startswith("[Image:"):
            continue
        rows.append((ts[:10], c))
rows.sort()
print(f"operator messages: {len(rows)}   interrupts (cut the model off): {interrupts}")
cor = [(d, t) for d, t in rows if len(t) < 500 and CORRECT.search(t)]
res = [(d, t) for d, t in rows if len(t) < 500 and RESTART.search(t)]
print(f"corrections: {len(cor)}   restart-nudges ('keep going'): {len(res)}")
print(f"\nby day: {dict(collections.Counter(d for d, _ in cor))}")
print("\n--- corrections, newest last (the next person should not reach these) ---")
for d, t in cor[-18:]:
    print(f"  {d}  {t[:150]!r}")
if res:
    print("\n--- restart nudges (the run did not finish in one shot) ---")
    for d, t in res[-8:]:
        print(f"  {d}  {t[:120]!r}")
PY
emit_cmd python3 "$TMPD/friction.py" "$DAYS"
emit '```'
emit ""

# ── 3 · the last workflow run, per phase ─────────────────────────────────────
emit "## 3 · The last workflow run — where the wall clock went"
emit ""
emit '```'
cat > "$TMPD/runs.py" <<'PY'
import json, glob, os
proj = os.path.expanduser("~/.claude/projects")
runs = []
for d in glob.glob(proj + "/-Users-toc-Server-one-ie*/*/workflows/*.json"):
    try:
        runs.append((os.path.getmtime(d), d))
    except Exception:
        pass
if not runs:
    print("no workflow run records found")
else:
    runs.sort(reverse=True)
    for _, p in runs[:2]:
        try:
            d = json.load(open(p))
        except Exception:
            continue
        dur = int(d.get("durationMs") or 0)
        print(f"\n{d.get('workflowName','?')}  {dur/60000:.1f}min  "
              f"{d.get('totalTokens',0):,}tok  {d.get('agentCount','?')}agents  "
              f"status={d.get('status','?')}")
        ag = [w for w in d.get("workflowProgress", []) if w.get("type") == "workflow_agent"]
        if not ag or not d.get("startTime"):
            continue
        st = int(d["startTime"]); end = st + dur
        marks = sorted((int(a["startedAt"]), a.get("label", "?"),
                        a.get("phaseTitle", "?"), a.get("cached")) for a in ag if a.get("startedAt"))
        for i, (t, lab, ph, cached) in enumerate(marks):
            nxt = marks[i + 1][0] if i + 1 < len(marks) else end
            el = (nxt - t) / 60000
            par = sum(1 for m in marks if abs(m[0] - t) < 3000)
            flag = "CACHED" if cached else ""
            par_s = f"(x{par} parallel)" if par > 1 else "(serial)"
            print(f"  {lab:26s} {ph:11s} {el:6.2f}m {100*el*60000/max(dur,1):5.1f}%  {par_s} {flag}")
        print("  → a phase over ~25% is the target. Serial phases with a high share are the")
        print("    first question: was that order REQUIRED, or just the order it was written in?")
PY
emit_cmd python3 "$TMPD/runs.py"
emit '```'
emit ""

# ── 4 · the doors — where a learning must land to reach the next person ───────
emit "## 4 · The doors — where a finding has to land, or it does not count"
emit ""
emit "A finding written into a report is paid for once and helps nobody. Each door below"
emit "auto-loads for a defined audience. Pick the narrowest door that covers the path."
emit ""
emit "| door | loads when | use it for |"
emit "|---|---|---|"
emit "| \`.claude/rules/<x>.md\` | a file matching its \`paths:\` glob is touched | a trap specific to a FILE TYPE or directory |"
emit "| \`.claude/CLAUDE.md\` | every session in this repo | harness behaviour: hooks, commands, lanes |"
emit "| \`one-ie/CLAUDE.md\` | every session in this repo | substrate law, the locked names, the don'ts |"
emit "| \`one.ie/ai/agents/<a>/agent.md\` | that agent is spawned | a standing brief typed by hand more than twice |"
emit "| \`.claude/commands/<c>.md\` | \`/<c>\` is invoked | the gate order and refusals for one command |"
emit "| \`~/.claude/projects/-Users-toc-Server-one-ie/memory/\` | recalled by relevance | a non-derivable fact + why + how to apply |"
emit "| \`text/<slug>-plan.md\` | read on purpose | the measurement and the reasoning behind a change |"
emit ""
emit "Rules currently wired, with their globs (a rule that loses its \`paths:\` starts loading"
emit "on EVERY turn, silently — that is why this list is printed):"
emit '```'
for f in .claude/rules/*.md; do
  [ -f "$f" ] || continue
  globs="$(awk '/^paths:/{f=1;next} /^---/{if(f)exit} f&&/^ *- /{gsub(/^ *- *"?|"?$/,"");printf "%s ",$0}' "$f")"
  if [ -z "$globs" ]; then
    emit "  $(basename "$f")  *** NO paths: — LOADS EVERY TURN ***"
  else
    emit "  $(basename "$f")  →  $globs"
  fi
done
emit '```'
emit ""

# ── 5 · the close ────────────────────────────────────────────────────────────
emit "## 5 · Close this retro properly"
emit ""
emit "1. Pick the friction from §2 that cost the most, and that is still live."
emit "2. Ask the discriminating question: **was there a rule and it was ignored, or was"
emit "   there no rule?** A rule ignored needs a hook or a gate — text will not fix it."
emit "   A rule missing needs text, in the narrowest door from §4 that covers the path."
emit "3. Write it, with the measurement that justifies it. A trap without its number gets"
emit "   deleted by the next person who doubts it."
emit "4. Say which lane ran. A fast pass is never reported as a full pass."
emit "5. If nothing is worth landing, say that. An honest empty retro beats an invented one."
emit ""
[ -n "$OUT" ] && echo "[retro] brief written to $OUT" >&2
exit 0
